version: '3'

services:
  gocqhtpp:
    container_name: gocqhttp
    environment: 
      - TZ=Asiz/Singapore
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./gocqhttp:/usr/src/app:delegated
    build:
      context: ./gocqhttp

  ioabot:
    container_name: ioabot
    environment:
      - TZ=Asia/Singapore
      - DATABASE_URI=postgresql://root:password@postgres:5432/ioabot
    ports:
      - 8702:8702
    depends_on:
      - postgres
    build:
      context: ./bot
    image: bubbleioa/ioa-bot:latest

  postgres:
    container_name: postgres
    environment:
      - TZ=Asia/Singapore
      - PGTZ=Asia/Singapore
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ioabot
    image: postgres:13.1-alpine

networks:
  default:
    name: ioabot-default